name: ecub_delivery
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.3.0
  google_fonts: 4.0.4
  fluttertoast: ^8.2.8
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.1.4
  google_maps_flutter: ^2.9.0
  location: ^5.0.3
  url_launcher: ^6.1.10
  http: ^0.13.5
  flutter_map: ^3.0.0
  latlong2: ^0.8.1
  geolocator: ^12.0.0
  webview_flutter: ^4.9.0
  flutter_polyline_points: ^1.0.0
  logging: ^1.2.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  flutter_tts: ^4.0.2
  logger: ^2.4.0
  intl: ^0.18.0
  image_picker: ^1.0.4
  firebase_storage: ^12.1.3
  google_places_flutter: ^2.0.5
  carousel_slider:
    git:
      url: https://github.com/serenader2014/flutter_carousel_slider.git
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  cloud_firestore: ^5.2.1
  flutter_launcher_icons: ^0.13.1

# flutter_launcher_icons:
#   android: true
#   ios: true
#   image_path: "assets/logo.png"
#   min_sdk_android: 23
#   remove_alpha_ios: true
#   adaptive_icon_background: "#FFFFFF"
#   adaptive_icon_foreground: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/