name: ecub_delivery
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.2
  google_fonts: ^4.0.4
  fluttertoast: ^8.2.12
  cloud_firestore: ^5.6.12
  firebase_auth: ^5.7.0
  google_maps_flutter: ^2.12.3
  location: ^5.0.3
  url_launcher: ^6.3.2
  http: ^0.13.6
  flutter_map: ^3.1.0
  latlong2: ^0.8.2
  geolocator: ^12.0.0
  webview_flutter: ^4.13.0
  flutter_polyline_points: ^1.0.0
  logging: ^1.3.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  flutter_tts: ^4.2.3
  logger: ^2.6.1
  intl: ^0.18.1
  image_picker: ^1.0.4
  firebase_storage: ^12.4.10
  google_places_flutter: ^2.1.0
  carousel_slider: ^5.1.1
  shared_preferences: ^2.5.3
  razorpay_flutter: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

# flutter_launcher_icons:
#   android: true
#   ios: true
#   image_path: "assets/logo.png"
#   min_sdk_android: 23
#   remove_alpha_ios: true
#   adaptive_icon_background: "#FFFFFF"
#   adaptive_icon_foreground: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/Tick.gif